### ISSUE TITLE
Can Sentry capture user-agent info with your extension?

### ISSUE THREAD

**Issue by newscloud** [notamedia/yii2-sentry#11]
I'm not seeing user agent info in my sentry issues. Do you know if there is a way to activate it? Or is it not possible. https://github.com/samdark says rollbar collects this info.

Thanks!

**Comment by niksamokhvalov** [comment]
In our projects SentryTarget correctly collects information about the request: headers, user agent, URL, query, etc. Can you give examples of application configuration and your logs?

**Comment by newscloud** [comment]
Will look at this soon. Thanks for the reply.
