### ISSUE TITLE
В senrty приходит 2 сообщения по одной ошибке

### ISSUE THREAD

**Issue by SmotrovaLilit** [notamedia/yii2-sentry#13]
Настроила таким образом:
```
        'log' => [
            'targets' => [
                [
                    'class' => \notamedia\sentry\SentryTarget::className(),
                    'dsn' => $params['sentry_url'],
                    'levels' => ['error', 'warning']
                ],
            ],
        ],
```
Код который вызывает ошибку 
```
        $k = null;
        $k->fasfdasdsar5();
```

В результате в sentry пришло 2 ошибки 
![image](https://user-images.githubusercontent.com/8288964/28127454-48958a6c-6735-11e7-8c98-3d217999537e.png)

В одном сообщении подробное описание, прям на какой строчке ошибка, а в другом просто текст ошибки.

Я думаю вызвано это тем что Yii ошибку на два сообщения в логах разбивает. Можно попробовать при отправке исключить  одно из сообщений.

**Comment by niksamokhvalov** [comment]
Дело в том, что Raven автоматически регистрирует свой хендлер: https://docs.sentry.io/clients/php/usage/.

**Comment by vitalyzhakov** [comment]
Воспроизводится.
То есть дополнительная отправка лишняя?
Требует правки компоненты?

Настроил похожее расширение https://github.com/hellowearemito/yii2-sentry, дублирующих ошибок нет.

**Comment by niksamokhvalov** [comment]
Судя по всему, в версии 1.4.0 проблема уже не воспроизводится. Пожалуйста, переоткройте проблему, если это не так.
