### ISSUE TITLE
Support for new Sentry Version 2

### ISSUE THREAD

**Issue by Julian-B90** [notamedia/yii2-sentry#20]
Plz Support the new Version 2 

https://github.com/getsentry/sentry-php

**Comment by Julian-B90** [comment]
i have made a PR with the new Version from sentry #22

**Comment by DarthLegiON** [comment]
@niksamokhvalov @Julian-B90 can we rush this update process? I see you have problem with tests passing in your PR. Do you need some help?

**Comment by Julian-B90** [comment]
The issue in my test was that the GIT Hub Auth Token are missing for Travis. This i an issue for @niksamokhvalov or @notamedia
