### ISSUE TITLE
ClientOptions is never used

### ISSUE THREAD

**Issue by DarthLegiON** [notamedia/yii2-sentry#26]
Hello!

I want to use parameter `release` in `\Sentry\init` (like [here](https://docs.sentry.io/workflow/releases/?_ga=2.265319887.1333652797.1571656049-778771601.1565960597%3F_ga&platform=php#configure-sdk)) and it is impossible because no extra parameters are passed into this function. `clientOptions` property is never used in `SentryTarget`, but it could be used for passing such parameters into Sentry client. 

How can I quickly change this, or PR needed?

**Comment by niksamokhvalov** [comment]
Thanks!
