### ISSUE TITLE
No session in Sentry issues

### ISSUE THREAD

**Issue by DarthLegiON** [notamedia/yii2-sentry#29]
Hello!

I've updated this plugin version from v1 to v2 and added clientOptions: release and environment. But Sentry doesn't receive my session variables now. 

Here is Sentry target config:
```php
[
                    'class' => SentryTarget::class,
                    'dsn' => 'DSN',
                    'levels' => ['error', 'warning'],
                    'except' => [
                        'yii\web\HttpException:400',
                        'yii\web\HttpException:403',
                        'yii\web\HttpException:404',
                    ],
                    'clientOptions' => [
                        'release' => 'version tag',
                        'environment' => 'prod',
                    ],
                    'context' => true,
                ]
```

My session is stored in redis (but this is working about a couple of years):
```php
'session' => [
            'class' => Session::class,
            'redis' => 'redis',
            'timeout' => 86400,
        ],
```

Due to this issue I can't recognize users in Sentry. What could be wrong?

**Comment by DarthLegiON** [comment]
UPD: Also no user IP is sent by PHP.

**Comment by DarthLegiON** [comment]
I suppose no extra info (context included) is sending by new plugin version. See `SentryTarget:75`: `Sentry::captureException` accepts only 1 argument and `$data` just isn't used anywhere. If message isn't Exception, the same thing happens: `$data['extra']['context']` is collected but never used. It breaks this functionality completely. I don't know how to fix it but will try when I'll have time.

**Comment by CookiesEater** [comment]
Hi, can you check the latest version (1.5.0 beta), please? Extra context was added to exception scope.
