### ISSUE TITLE
Support composer without composer.lock

### ISSUE THREAD

**Issue by honsa** [notamedia/yii2-sentry#34]
Hello

Thank you for this nice extension.

We are working in development without .lock file. If we try to install your extension the message 

> [LogicException]                                   
> No lockfile found. Unable to read locked packages

appears. I can create a lock file temporary but I think it should also work without.

**Comment by dmhaiduchonak** [comment]
Please show steps how to reproduce this problem.

**Comment by honsa** [comment]
Delete your composer.lock or set lock to false in composer.json. 

Without composer.lock file in the project dir the exception appears.

**Comment by dmhaiduchonak** [comment]
@honsa try
`composer require --no-plugins notamedia/yii2-sentry`

I have no other solutions.
See https://github.com/composer/composer/issues/8336
