### ISSUE TITLE
No stack trace included in logged errors

### ISSUE THREAD

**Issue by timkelty** [notamedia/yii2-sentry#35]
I have this configured exactly as your example shows (https://github.com/notamedia/yii2-sentry#installation), and errors are logged to Sentry, but they don't include any stack trace.

Is this correct? Do I need to use the `extraCallback` to include stack trace data?

**Comment by dmhaiduchonak** [comment]
Yes, it's correct. Did you set YII_DEBUG to true?

**Comment by vitalyzhakov** [comment]
Hello!

According to official docs https://www.yiiframework.com/doc/guide/2.0/en/structure-entry-scripts#defining-constants YII_DEBUG must be disabled in production.

But we find useful, when in sentry error (or warning) page will show stack trace.

How can be trace added only for sentry logging messages?

**Comment by vitalyzhakov** [comment]
Hello!
@dmhaiduchonak , @niksamokhvalov ?

**Comment by CookiesEater** [comment]
Hi! Can you provide please example of stack trace and errors when in Sentry does not catch data? For exceptions stack trace should be shown in Sentry regardless of YII_DEBUG value

**Comment by vitalyzhakov** [comment]
Hello!

Exceptions are recording with stack trace.

But [Yii::error()](https://www.yiiframework.com/doc/api/2.0/yii-baseyii#error()-detail) call does not record stack trace.

If I set global log [traceLevel](https://www.yiiframework.com/doc/api/2.0/yii-log-logger#$traceLevel-detail) more than 0, trace is shown.

But in official docs it is not recommended 

Now I have overrided Logger class
https://github.com/yiisoft/yii2/blob/master/framework/log/Logger.php#L151
```php
class Logger extends \yii\log\Logger
{
    public function log($message, $level, $category = 'application')
    {
        $time = microtime(true);
        $traces = [];
        if ($this->canTrace($level)) { // <- this line changed
            $count = 0;
            $ts = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
            array_pop($ts); // remove the last trace since it would be the entry script, not very useful
            foreach ($ts as $trace) {
                if (isset($trace['file'], $trace['line']) && strpos($trace['file'], YII2_PATH) !== 0) {
                    unset($trace['object'], $trace['args']);
                    $traces[] = $trace;
                    if (++$count >= $this->traceLevel) {
                        break;
                    }
                }
            }
        }
        $this->messages[] = [$message, $level, $category, $time, $traces, memory_get_usage()];
        if ($this->flushInterval > 0 && count($this->messages) >= $this->flushInterval) {
            $this->flush();
        }
    }

    private function canTrace($level)
    {
        if (defined('YII_DEBUG')) {
            return true;
        } else {
            return in_array($level, [self::LEVEL_ERROR, self::LEVEL_WARNING]);
        }
    }
}
```
Works for me, but record trace for all log targets.

**Comment by CookiesEater** [comment]
Now I understand, thanks. Yes, if you need custom logic to attaching the stack trace you need your own logger class.
At the moment, yii2-sentry does not collect the stack trace from Yii logger (only for exceptions)
If needed, please open a new issue for stack trace attaching to errors and other messages to sentry
