### ISSUE TITLE
Add ip address

### ISSUE THREAD

**Issue by chrisc0** [notamedia/yii2-sentry#36]
Hi, if you could add the ability to include the user's ip address, that would be helpful.  I'm not very good with git but this is how I was able to get it working for me.  In SentryTarget I added this function:

	function getUserIpAddr(){
		if(!empty($_SERVER['HTTP_CLIENT_IP'])){
			//ip from share internet
			$ip = $_SERVER['HTTP_CLIENT_IP'];
		}elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
			//ip pass from proxy
			$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
		}else{
			$ip = $_SERVER['REMOTE_ADDR'];
		}
		return $ip;
	}

Then I added this piece of code in the export function just after the $data array near the top:

            $userIp = $this->getUserIpAddr();
			if (!empty($userIp)) {
				\Sentry\configureScope(function (\Sentry\State\Scope $scope) use ($data, $userIp): void {
					$scope->setUser(['ip' => $userIp]);
				});
			}

**Comment by CookiesEater** [comment]
Hi, can you check the latest version (1.5.0 beta), please? IP logging was added to it.
