### ISSUE TITLE
Probable bug in passing extra data while processing an exception

### ISSUE THREAD

**Issue by kryvel** [notamedia/yii2-sentry#39]
I think there is a bug in passing extra data while processing an exception

vendor/notamedia/yii2-sentry/src/SentryTarget.php:76
```
if ($text instanceof \Throwable || $text instanceof \Exception) {
                $data = $this->runExtraCallback($text, $data);
                \Sentry\captureException($text, $data);
                continue;
            } 
```
there  `\Sentry\captureException($text, $data);` we pass two arguments to function captureException. But function accept only one. 
```
/**
 * Captures an exception event and sends it to Sentry.
 *
 * @param \Throwable $exception The exception
 */
function captureException(\Throwable $exception): ?string
{
    return SentrySdk::getCurrentHub()->captureException($exception);
}
```
 So second argument with extra data, provided by extraCallback is just ignored.

**Comment by CookiesEater** [comment]
Hi! Can you check 1.5.0-beta version please? This has been fixed there

**Comment by kryvel** [comment]
Thanks, fixed.
