### ISSUE TITLE
except doesn't work for SentryTarget configuration

### ISSUE THREAD

**Issue by nikosid** [notamedia/yii2-sentry#44]
This is my log configuration:
```
                'sentry' => [
                    'class' => SentryTarget::class,
                    'dsn' => env('SENTRY_DSN'),
                    'levels' => ['error', 'warning'],
                    'except' => [
                        'yii\web\HttpException:40*'
                    ],
                    'enabled' => !empty(env('SENTRY_DSN')),
                ],
```
But I'm still getting 404 error in sentry log.
I checked the same syntax in other Log targets end it works.
Can you help me to find out what is wrong or fix the problem?

**Comment by CookiesEater** [comment]
Hi!
Yes, Sentry registers own handler and sent all events, it was fixed in https://github.com/notamedia/yii2-sentry/pull/42 and will be released soon
