### ISSUE TITLE
ALARM 1.5.1

### ISSUE THREAD

**Issue by antivir88** [notamedia/yii2-sentry#45]
PHP message: PHP Notice:  Trying to get property 'enabled' of non-object in /vendor/yiisoft/yii2/log/Dispatcher.php on line 187

**Comment by CookiesEater** [comment]
Hi! Provide please config part of log with Sentry target. This is relevant only for 1.5.1 version?

**Comment by antivir88** [comment]
Downgrade version to 1.5.0 fixed this bug

**Comment by antivir88** [comment]
'log' => [
        'traceLevel' => YII_DEBUG ? 3 : 0,
        'targets' => [
            [
                'class' => 'notamedia\sentry\SentryTarget',
                'dsn' => '____',
                'levels' => ['error', 'warning'],
                'context' => true // Write the context information. The default is true.
            ],
        ],
    ],

**Comment by CookiesEater** [comment]
Sorry, but I can't reproduce this with yii2-app-basic application. Can you provide, please, more info? When this error happen? May be you can check in another application if this error will occur?
