### ISSUE TITLE
Argument 1 passed to Sentry\Options::setIntegrations() must be of the type array

### ISSUE THREAD

**Issue by liviuk2** [notamedia/yii2-sentry#46]
Hi,
I installed and configured the extension but when I run my app I get the following error:

![screenshot-php71local-2020 09 03-10_32_34](https://user-images.githubusercontent.com/11991766/92091334-e8076280-edd0-11ea-814b-7884c59d374a.png)

What can I do?

**Comment by CookiesEater** [comment]
Hi! Please update sentry/sdk to 2.1+ from composer

**Comment by ccchapman** [comment]
I was unable to resolve this issue by requiring `sentry/sdk:^2.1` due to constraint conflicts. Downgrading to `notamedia/yii2-sentry:1.5.0` resolved the issue.

**Comment by CookiesEater** [comment]
Hi! Please check 1.6.0-beta version to resolve issue
