### ISSUE TITLE
Ability to include performance monitoring

### ISSUE THREAD

**Issue by chrisc0** [notamedia/yii2-sentry#47]
Hi, 

Can you please add the ability to enable performance monitoring like this:

```
Sentry\init([
  'dsn' => 'https://examplePublicKey@o0.ingest.sentry.io/0',
  'traces_sample_rate' => 1.0 # be sure to lower this in production to prevent quota issues
]);
```
as described on this page:
[https://docs.sentry.io/platforms/php/](https://docs.sentry.io/platforms/php/)

I believe this was recently added in version 3 of the Sentry SDK.

Thanks!

**Comment by CookiesEater** [comment]
Hi! Please check 1.6.0-beta release, this can be used like this:

```
[
    'class' => \notamedia\sentry\SentryTarget::class,
    'dsn' => 'xxx',
    'clientOptions' => [
        'traces_sample_rate' => 1.0,
    ],
],
```

**Comment by chrisc0** [comment]
Yes, this works now but the 'excluded_exception' option no longer works like in the previous version.  The option can be [seen here](https://docs.sentry.io/clients/php/config/) in the docs.  Before I included this in the clientOptions array:

```
'excluded_exceptions' => [
        'yii\web\NotFoundHttpException',
],
```

**Comment by CookiesEater** [comment]
`excluded_exceptions` is not supported in sentry 3.0 (it's can be done with `IgnoreErrorsIntegration`, but custom integrations not supported by now)

You can use Yii2 `except` mechanism to achieve this (https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging#message-filtering), like
```
'class' => \notamedia\sentry\SentryTarget::class,
'except' => [
    'yii\web\HttpException:404',
],
'dsn' => 'xxx',
'clientOptions' => [
    'traces_sample_rate' => 1.0,
],
```

**Comment by webparadoxer** [comment]
У кого то заработал perfomance мониторинг? пробовали и 1.6 и 1.7 - не прилетает ничего

**Comment by webparadoxer** [comment]
any updates?

**Comment by CookiesEater** [comment]
Do you wrap code in transactions as it say in docs: https://docs.sentry.io/platforms/php/performance/ ?

**Comment by CookiesEater** [comment]
Please open another issue if you don't receive stats after wrapped code in transaction and setting `traces_sample_rate`
