### ISSUE TITLE
Out of Memory Exceptions (Fatal Errors) are not being send to sentry

### ISSUE THREAD

**Issue by ItsReddi** [notamedia/yii2-sentry#48]
## Steps to reproduce.
1. Configure extension
2. add somewhere e.g in a view `$a = str_repeat("Hello", 4242000000);`  (Memory exception)
3. run the view

### Environment
PHP: 7.4.9
Yii2: 2.0.37
notamedia/yii2-sentry: latest

### Expected: New event in sentry
Behavior:
- Nothing logged
1. php-sentry tracked via xdebug is called and the exception should be sent
2. if we change the handleFatalError() in `base/ErrorHandler.php` to not `exit(1)` the exception is logged

![grafik](https://user-images.githubusercontent.com/3147888/95721372-c83a4880-0c72-11eb-98b3-c56693ec8081.png)

It feels that the errors are not logged because the proccess is ended before sending?

**Comment by CookiesEater** [comment]
Hi! Please check 1.6.0-beta release, this is fixed in sentry 3.0

**Comment by ItsReddi** [comment]
I can confirm that these errors are now send
