### ISSUE TITLE
How collect js error?

### ISSUE THREAD

**Issue by nohnaimer** [notamedia/yii2-sentry#50]
Hi,
How to collect error javascript? I use old [yii2-sentry](https://github.com/hellowearemito/yii2-sentry) with sdk 1. I would like to update, but js errors needs.
Any ideas how use you module and add js errors?

**Comment by CookiesEater** [comment]
Hi! To collect js errors you need manually include sentry js script on page (for example, in root template) and init it as said in documentation:
https://docs.sentry.io/platforms/javascript/install/cdn/

**Comment by nohnaimer** [comment]
https://github.com/notamedia/yii2-sentry/pull/52
