### ISSUE TITLE
Silently die on PHP < 7.2

### ISSUE THREAD

**Issue by petr-panek** [notamedia/yii2-sentry#53]
On PHP < 7.2 it silently die without any error message.
Probably caused by Sentry SDK that require PHP 7.2.

Is any error message possible in such a case?
Not urgent, but may save some time to other developpers facing the similar situation like me (apache PHP 8.0, shell PHP 7.1).

Thank you :-)

**Comment by CookiesEater** [comment]
Hi! Yes, this library isn't work with php < 7.2

Do you try with:
```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
?

**Comment by petr-panek** [comment]
No, I didn't try.
After some tests I had suspicion that it's caused by PHP version, composer.json confirmed it.

Hopefully I car run "php8.0" instead of "php". 
It's an experience, if apache use PHP 8 it doesn't mean that shell must too :-)

**Comment by niksamokhvalov** [comment]
You can use version [1.5.1](https://github.com/notamedia/yii2-sentry/releases/tag/1.5.1) (or lower) that requirement PHP 7.1.
