### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by jory3** [notamedia/yii2-sentry#56]
It'd be great to be able to enable performance monitoring like described in Sentry Docs
https://docs.sentry.io/platforms/php/#performance-monitoring

```
\Sentry\init([
  'dsn' => 'https://examplePublicKey@o0.ingest.sentry.io/0',
  'traces_sample_rate' => 1.0 # be sure to lower this in production to prevent quota issues
]);
```

**Comment by CookiesEater** [comment]
Hi! You can use it for now like this:
```
[
    'class' => \notamedia\sentry\SentryTarget::class,
    'dsn' => 'xxx',
    'clientOptions' => [
        'traces_sample_rate' => 1.0,
    ],
]
```

But by default it do nothing, for results you need to wrap you code with transactions as said in documentations: https://docs.sentry.io/platforms/php/performance/
