### ISSUE TITLE
Performace Monitoring Issue

### ISSUE THREAD

**Issue by MageloPST** [notamedia/yii2-sentry#58]
Hello, I have a Yii2 project using the advanced template, and have configured the Sentry logs as follow:

```
'log' => [
    ...
    [
        // Sentry logging
        'class' => \notamedia\sentry\SentryTarget::class,
        'dsn' => <SENTRY_DSN>,
        'levels' => ['error', 'warning'],
        'clientOptions' => [
            //'traces_sample_rate' => 1.0,
            'traces_sampler' =>  static function (\Sentry\Tracing\SamplingContext $context): float {
                // Test sample rate for all transactions
                return 1.0;
            }
        ],
    ]
    ...
]
```
The piece of code above is located at the `<source_directory>/common/config/main.php` file and it is being properly loaded in the project. For the matter of testing I have returned `return 1.0` for all the cases.

No with that configuration, I'm able to get proper logs of the exceptions occurring on the system, but I'm not getting anything in the Performance menu. Perhaps I'm doing something wrong?

I would like to see what is described here https://docs.sentry.io/platforms/php/#performance-monitoring

Thanks in advance!

**Comment by CookiesEater** [comment]
Hi!
By default no data is sent
You need to wrap necessary code for monitoring by Sentry Transaction, please check this docs for details: https://docs.sentry.io/platforms/php/performance/
